"""initial schema — AutoBOM Phase 1 baseline (20 tables)

Revision ID: 0001
Revises:
Create Date: 2026-07-19
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stream', sa.Enum('critical', 'main', name='batchstream', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('pending', 'written', name='batchstate', native_enum=False), nullable=False),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('cart_url', sa.String(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('written_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches'))
    )
    op.create_table('configuration',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_configuration'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('for_roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('unread', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.Enum('action', 'fyi', name='notificationkind', native_enum=False), nullable=False),
    sa.Column('source_role', sa.String(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('action_label', sa.String(), nullable=True),
    sa.Column('verb', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('who', sa.String(), nullable=True),
    sa.Column('when', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('type_label', sa.String(), nullable=True),
    sa.Column('routes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('go', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('storage_location_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('partsbox_location_ref', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ownership', sa.String(), nullable=True),
    sa.Column('autobom_managed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_location_metadata'))
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('api_status', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('primary_role', sa.String(), nullable=True),
    sa.Column('overrides', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('intern', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('invited_by', sa.String(), nullable=True),
    sa.Column('last_active', sa.String(), nullable=True),
    sa.Column('role_source', sa.Enum('seed', 'azure_group', name='rolesource', native_enum=False), nullable=False),
    sa.Column('azure_ad_object_id', sa.String(), nullable=True),
    sa.Column('last_role_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ts', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('before', sa.Text(), nullable=True),
    sa.Column('after', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit'))
    )
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('thread_level', sa.Enum('overall', 'line', name='commentthreadlevel', native_enum=False), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_table('force_waivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.CheckConstraint('length(reason) >= 10', name=op.f('ck_force_waivers_reason_min_length')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_force_waivers_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_force_waivers'))
    )
    op.create_table('programs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Paused', 'Complete', 'Archived', name='programstatus', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('started', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notify_on_equivalent_swap', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_programs_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs'))
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('lead_id', sa.String(), nullable=True),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'complete', 'archived', name='projectstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['users.id'], name=op.f('fk_projects_lead_id_users')),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_projects_program_id_programs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('draft', 'active', 'order-requested', 'ordered', 'ready', 'recommendation-sent', 'closed', name='collectionstate', native_enum=False), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('req_id', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_collections_owner_id_users')),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_collections_program_id_programs')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_collections_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections'))
    )
    op.create_table('cpn_issuance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cpn', sa.String(), nullable=False),
    sa.Column('scope', sa.Enum('project', 'wall', name='cpnscope', native_enum=False), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('wall_location', sa.String(), nullable=True),
    sa.Column('format_version', sa.Integer(), nullable=False),
    sa.Column('fulfillment_state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_cpn_issuance_program_id_programs')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_cpn_issuance_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cpn_issuance'))
    )
    op.create_table('requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('collection', 'bom', name='requestkind', native_enum=False), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('from_user_id', sa.String(), nullable=True),
    sa.Column('from_role', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('bucket_state', sa.Enum('QUEUED_MAIN', 'QUEUED_CRITICAL', 'WRITTEN', 'PURCHASED', 'PROCESSED', name='bucketstate', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resubmit', sa.Boolean(), nullable=False),
    sa.Column('items_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_requests_from_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_requests_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests'))
    )
    op.create_table('boms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('draft', 'validated', 'sourcing', 'results', 'normalised', 'submitted', 'exceptions', name='bomstate', native_enum=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('build_qty', sa.Integer(), nullable=True),
    sa.Column('overage', sa.Integer(), nullable=True),
    sa.Column('source_collection_id', sa.String(), nullable=True),
    sa.Column('partsbox_ref', sa.String(), nullable=True),
    sa.Column('validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_boms_owner_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_boms_project_id_projects')),
    sa.ForeignKeyConstraint(['source_collection_id'], ['collections.id'], name=op.f('fk_boms_source_collection_id_collections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boms')),
    sa.UniqueConstraint('project_id', name='one_master_bom_per_project')
    )
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('mpn', sa.String(), nullable=True),
    sa.Column('mfr', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('supplier_pn', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ext_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_items_collection_id_collections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_items')),
    sa.UniqueConstraint('collection_id', 'line_no', name='line_no_unique_per_collection')
    )
    op.create_table('bom_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bom_id', sa.String(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('mpn', sa.String(), nullable=True),
    sa.Column('mfr', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('supplier_pn', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ext_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ex_reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_by', sa.String(), nullable=True),
    sa.Column('replacement', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('cpn', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], name=op.f('fk_bom_lines_bom_id_boms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bom_lines')),
    sa.UniqueConstraint('bom_id', 'line_no', name='line_no_unique_per_bom')
    )
    op.create_table('bom_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bom_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_bom_versions_actor_id_users')),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], name=op.f('fk_bom_versions_bom_id_boms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bom_versions')),
    sa.UniqueConstraint('bom_id', 'version', name='version_unique_per_bom')
    )
    op.create_table('builds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('bom_id', sa.String(), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('build_qty', sa.Integer(), nullable=True),
    sa.Column('overlay', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('qr_url', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_builds_actor_id_users')),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], name=op.f('fk_builds_bom_id_boms')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_builds_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_builds'))
    )
    op.create_table('pushbacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bom_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Enum('obsolete', 'eol', 'unsourceable', 'zero-stock', 'missing-component', 'other', name='pushbackreason', native_enum=False), nullable=False),
    sa.Column('urgency', sa.Enum('blocking', 'standard', name='pushbackurgency', native_enum=False), nullable=False),
    sa.Column('from_user_id', sa.String(), nullable=True),
    sa.Column('to_user_id', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('open', 'deferred', 'resolved', 'cancelled', name='pushbackstate', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('loop', sa.Integer(), nullable=True),
    sa.Column('flagged_lines', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('added_component_request', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('recommendation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('resolved_at_version_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], name=op.f('fk_pushbacks_bom_id_boms')),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_pushbacks_from_user_id_users')),
    sa.ForeignKeyConstraint(['resolved_at_version_id'], ['bom_versions.id'], name=op.f('fk_pushbacks_resolved_at_version_id_bom_versions')),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_pushbacks_to_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pushbacks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pushbacks')
    op.drop_table('builds')
    op.drop_table('bom_versions')
    op.drop_table('bom_lines')
    op.drop_table('collection_items')
    op.drop_table('boms')
    op.drop_table('requests')
    op.drop_table('cpn_issuance')
    op.drop_table('collections')
    op.drop_table('projects')
    op.drop_table('programs')
    op.drop_table('force_waivers')
    op.drop_table('comments')
    op.drop_table('audit')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('storage_location_metadata')
    op.drop_table('notifications')
    op.drop_table('configuration')
    op.drop_table('batches')
    # ### end Alembic commands ###
