/* global React, Icon, StatusBadge, RoleTag, SupplierTag, Banner, EmptyState, useStore, storeActions,
   getState, PROJECTS, fmtUSD */
/* AutoBOM — Embedded surfaces (Purchasing v4 + Inventory/Receiving/Programs shells).
   Purchasing and Inventory are NOT login roles. They are surfaces embedded inside the
   Designer and Production workspaces, reachable from those sidebars. */
const { useState: useStateEmb, useEffect: useEffEmb } = React;

/* CPN is generated by the canonical window.cpnFor (data.jsx) — sigil format, read-only. */

/* Flatten requests → part rows carrying request context + sigil CPN. */
function partRows(requests) {
  const out = [];
  for (const r of requests) {
    (r.items || []).forEach((i, idx) => out.push({
      key: `${r.id}:${i.no ?? idx}`, reqId: r.id, project: r.project, from: r.from, fromRole: r.fromRole,
      submitted: r.submitted, critical: r.critical, bucketState: r.bucketState, sourceId: r.sourceId, sourceLabel: r.title,
      mpn: i.mpn, mfr: i.mfr, desc: i.desc, supplier: i.supplier, qty: i.qty, ext: i.ext, cpn: window.cpnFor(r, i), scope: window.cpnScope ? window.cpnScope(r) : 'project',
    }));
  }
  return out;
}

const fmtC = (m) => m >= 60 ? `${Math.floor(m / 60)}h ${m % 60}m` : `${m}m`;

/* Safe project-name lookup: static catalog, then the live store, then 'Other'
   (a Collection/Request may be Program-bound with no Project). */
function projName(pid) {
  if (!pid) return 'Other';
  const st = (typeof getState === 'function' && getState().projects) || {};
  const p = (typeof PROJECTS !== 'undefined' && PROJECTS[pid]) || st[pid];
  return (p && p.name) || 'Other';
}

/* ============================================================
   Embedded Purchasing view (v4) — Full / My submissions toggle.
   ============================================================ */
function EmbeddedPurchasing({ go, focusReq }) {
  const requests = useStore(s => s.requests);
  const batch = useStore(s => s.system.batch);
  const me = useStore(s => s.users.find(u => u.id === s.currentUserId));
  const activeRole = useStore(s => s.activeRole);
  // Admin opens Purchasing in Full mode by default; Designer/Production see their own submissions.
  const [mode, setMode] = useStateEmb(() => sessionStorage.getItem('autobom.purchasing.mode') || (activeRole === 'admin' ? 'full' : 'filtered'));
  const focusReqObj = focusReq ? requests.find(r => r.id === focusReq) : null;
  const focusInArchive = !!focusReqObj && (focusReqObj.bucketState === 'WRITTEN' || focusReqObj.bucketState === 'PURCHASED');
  const [tab, setTab] = useStateEmb(() => focusInArchive ? 'archive' : 'buckets');
  const setModeP = (m) => { setMode(m); sessionStorage.setItem('autobom.purchasing.mode', m); };

  const mine = (r) => r.from === (me && me.name);
  const inFlight = requests;
  const scoped = mode === 'filtered' ? inFlight.filter(mine) : inFlight;

  const preBatch = scoped.filter(r => r.bucketState === 'QUEUED_CRITICAL' || r.bucketState === 'QUEUED_MAIN');
  const criticalParts = partRows(preBatch.filter(r => r.bucketState === 'QUEUED_CRITICAL' || r.critical));
  const mainParts = partRows(preBatch.filter(r => !(r.bucketState === 'QUEUED_CRITICAL' || r.critical)));

  // Sent-to-sheet archive — batches that have been written (mocked from WRITTEN/PURCHASED requests).
  const written = scoped.filter(r => r.bucketState === 'WRITTEN' || r.bucketState === 'PURCHASED');
  const batches = buildArchive(written, mode, me);

  return (
    <div className="page">
      <div className="page-head">
        <div className="ph-titles">
          <div className="display" style={{ display: 'flex', alignItems: 'center', gap: 12 }}><Icon name="cart" size={24} />Purchasing</div>
          <div className="ph-sub">A shared view of what's queued and what's been sent to the Daily Purchasing List. Purchasing is not a role — it's a window anyone can look through.</div>
        </div>
        <div className="ph-actions">
          <div className="seg-toggle">
            <button className={mode === 'full' ? 'on' : ''} onClick={() => setModeP('full')}>Full</button>
            <button className={mode === 'filtered' ? 'on' : ''} onClick={() => setModeP('filtered')}>My submissions</button>
          </div>
        </div>
      </div>

      <div className="onedrive-banner">
        {/* Status banner, not a link. It used to render an external-link glyph
            with no href/onClick, so it read as clickable and did nothing. */}
        <span className="od-dot" /><Icon name="check" size={15} aria-hidden="true" />
        <div style={{ flex: 1 }}>
          <div style={{ fontWeight: 600 }}>Live integration — Daily Purchasing List (OneDrive)</div>
          <div className="caption">Critical batches every {fmtC(batch.critical.intervalMin)} · Main every {fmtC(batch.main.intervalMin)} · atomic writes · 14-column sheet unchanged, no CPN column.</div>
        </div>
      </div>

      <div className="tabs" style={{ margin: '4px 0 14px' }}>
        {[['buckets', 'Live buckets'], ['archive', 'Sent to sheet']].map(([k, l]) => (
          <div key={k} className={`tab${tab === k ? ' active' : ''}`} onClick={() => setTab(k)}>{l}</div>
        ))}
      </div>

      {tab === 'buckets' ? (
        <>
          <BucketSection critical parts={criticalParts} cfg={batch.critical} mode={mode} flashReq={focusReq} />
          <BucketSection parts={mainParts} cfg={batch.main} mode={mode} flashReq={focusReq} />
        </>
      ) : (
        <ArchiveSection batches={batches} mode={mode} flashReq={focusReq} />
      )}
    </div>
  );
}

function BucketSection({ critical, parts, cfg, mode, flashReq }) {
  const HEADERS = <tr><th>Part</th><th>CPN</th><th>Project</th>{mode === 'full' && <th>Requester</th>}<th>Supplier</th><th className="num">Qty</th><th className="num">Est. cost</th><th>Submitted</th></tr>;
  return (
    <div className="obs-section">
      <div className={`bucket-head${critical ? ' critical' : ''}`}>
        <span className="bucket-flag"><Icon name={critical ? 'alert' : 'layers'} size={14} />{critical ? 'CRITICAL' : 'MAIN BUCKET'}</span>
        <span className="bucket-count">{parts.length} part{parts.length === 1 ? '' : 's'}</span>
        <span className="batch-timer"><Icon name="clock" size={13} />next batch in {fmtC(cfg.nextRunMin)}</span>
      </div>
      {parts.length === 0 ? (
        <div className={`bucket-empty${critical ? ' critical' : ''}`}>No parts in {critical ? 'Critical' : 'Main'} bucket. Next batch in {fmtC(cfg.nextRunMin)}.</div>
      ) : (
        <div className="tbl-wrap flow"><table className="bom"><thead>{HEADERS}</thead><tbody>
          {parts.map(p => (
            <tr key={p.key} style={flashReq && p.reqId === flashReq ? { background: 'var(--action-soft)' } : undefined}>
              <td><div className="mono" style={{ fontWeight: 600 }}>{p.mpn}</div><div className="caption">{p.mfr}{p.desc && p.desc !== '—' ? ` · ${p.desc}` : ''}</div></td>
              <td><span className="cpn-cell"><span className="mono caption" title="Customer Part Number — read-only">{p.cpn}</span><span className={`scope-pill ${p.scope}`}>{p.scope}</span></span></td>
              <td className="secondary">{projName(p.project)}</td>
              {mode === 'full' && <td><RoleTag role={p.fromRole} /> <span className="caption">{p.from}</span></td>}
              <td>{p.supplier ? <SupplierTag supplier={p.supplier} /> : <span className="muted">—</span>}</td>
              <td className="num">{p.qty}</td>
              <td className="num mono">{p.ext != null ? fmtUSD(p.ext) : '—'}</td>
              <td className="caption">{p.submitted}</td>
            </tr>
          ))}
        </tbody></table></div>
      )}
    </div>
  );
}

/* Build sent-to-sheet archive batches. Each batch = one atomic write event. */
function buildArchive(written, mode, me) {
  if (written.length === 0) return [];
  // Group into two mock batches by critical flag for demonstration.
  const groups = { Critical: [], Main: [] };
  written.forEach(r => (r.critical ? groups.Critical : groups.Main).push(r));
  const batches = [];
  Object.entries(groups).forEach(([type, reqs]) => {
    if (reqs.length === 0) return;
    const lines = partRows(reqs);
    const received = lines.filter(l => l.bucketState === 'PURCHASED').length;
    batches.push({
      id: `BATCH-${type}-01`, type, when: type === 'Critical' ? 'Today 14:00' : 'Today 12:00',
      lines, total: lines.reduce((a, l) => a + (l.ext || 0), 0),
      received, count: lines.length,
    });
  });
  return batches;
}

function ArchiveSection({ batches, mode, flashReq }) {
  if (batches.length === 0) return <div className="card"><EmptyState icon="check" title="No batches sent yet." sub="When a batch timer fires, its rows are written to the Daily Purchasing List and appear here." /></div>;
  return <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>{batches.map(b => <ArchiveBatch key={b.id} batch={b} mode={mode} flashReq={flashReq} />)}</div>;
}

function ArchiveBatch({ batch, mode, flashReq }) {
  const [open, setOpen] = useStateEmb(() => !!flashReq && batch.lines.some(l => l.reqId === flashReq));
  const pct = batch.count ? Math.round(batch.received / batch.count * 100) : 0;
  return (
    <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
      <div className="panel-head" style={{ cursor: 'pointer' }} onClick={() => setOpen(o => !o)}>
        <Icon name={open ? 'chevdown' : 'chevright'} size={15} />
        <span className="ph-title">{batch.type} batch</span>
        <span className="mono caption">{batch.id}</span>
        <span className="ph-meta" style={{ marginLeft: 'auto', display: 'flex', gap: 14, alignItems: 'center' }}>
          <span>{batch.when}</span><span>{batch.count} rows</span>
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>{batch.received}/{batch.count} received
            <span className="mini-progress"><i style={{ width: pct + '%' }} /></span></span>
          <span className="mono" style={{ fontWeight: 700 }}>{fmtUSD(batch.total)}</span>
        </span>
      </div>
      {open && (
        <div className="tbl-wrap flow" style={{ border: 0 }}><table className="bom">
          <thead><tr><th>CPN</th><th>Part</th><th className="num">Qty</th><th>Supplier</th><th>Destination</th><th>Urgency</th><th>Fulfillment</th></tr></thead>
          <tbody>{batch.lines.map(l => {
            const state = l.bucketState === 'PURCHASED' ? 'full' : 'none';
            return (
              <tr key={l.key} style={flashReq && l.reqId === flashReq ? { background: 'var(--action-soft)' } : undefined}>
                <td><span className="cpn-cell"><span className="mono caption">{l.cpn}</span><span className={`scope-pill ${l.scope || 'project'}`}>{l.scope || 'project'}</span></span></td>
                <td className="mono" style={{ fontWeight: 600 }}>{l.mpn}</td>
                <td className="num">{l.qty}</td>
                <td>{l.supplier ? <SupplierTag supplier={l.supplier} /> : '—'}</td>
                <td className="secondary">{l.scope === 'wall' ? 'Wall' : projName(l.project)}</td>
                <td className="caption">{batch.type === 'Critical' ? 'Next Day' : '2-Day'}</td>
                <td>{state === 'full'
                  ? <span className="badge filled" style={{ background: 'var(--success)' }}><Icon name="check" size={11} />Fully received</span>
                  : <span className="badge outlined" style={{ color: 'var(--text-muted)' }}><Icon name="circle" size={10} />Not received</span>}</td>
              </tr>
            );
          })}</tbody>
        </table></div>
      )}
    </div>
  );
}

/* ============================================================
   Embedded Inventory / Receiving / Programs — shells (full build in next layer)
   ============================================================ */
function EmbeddedInventory({ go }) {
  const parts = useStore(s => s.inventory || []);
  const loading = useStore(s => s.inventoryLoading);
  /* The full part list is fetched HERE, on mount — not on session hydration.
     It measured ~1MB / ~10s, and every tab-open used to pay for it whether or
     not anyone opened Inventory. ensureInventory() is TTL'd and de-duped, so
     navigating away and back is free and two mounts share one request. */
  useEffEmb(() => { if (window.ensureInventory) window.ensureInventory(); }, []);
  const [q, setQ] = useStateEmb('');
  const [kind, setKind] = useStateEmb('all');
  const [cat, setCat] = useStateEmb('all');
  // Prefer live stats from the store. window.PARTSBOX_STATS starts life as a
  // bundled demo fixture (160 parts / 22 bins), so reading it first showed
  // fabricated counts until PartsBox finished loading.
  const liveStats = useStore(s => s.inventoryStats);
  const stats = liveStats || (parts.length
    ? { totalParts: parts.length, totalUnits: parts.reduce((a, p) => a + (p.onHand || 0), 0),
        distinctBins: new Set(parts.flatMap(p => (p.locations || []).map(l => l.name))).size }
    : { totalParts: 0, totalUnits: 0, distinctBins: 0 });
  const cats = ['all', ...[...new Set(parts.map(p => p.cat).filter(Boolean))].sort()];

  /* "Project boxes" / "Development wall" list the STORAGE LOCATIONS themselves,
     not the parts inside them. They used to filter the flat parts table down to
     any part that happened to sit in a matching location, which produced a long
     list of components rather than a list of boxes/bins. "All" remains the
     parts library. Location rows are aggregated out of the parts payload (each
     part carries its locations) and link into the existing storage detail page,
     which is keyed by location name. */
  const isLocView = kind === 'project' || kind === 'wall';

  const rows = isLocView ? [] : parts.filter(p => {
    if (cat !== 'all' && p.cat !== cat) return false;
    if (q && !(`${p.mpn} ${p.mfr} ${p.desc}`.toLowerCase().includes(q.toLowerCase()))) return false;
    return true;
  });

  const locMap = {};
  if (isLocView) {
    parts.forEach(p => (p.locations || []).forEach(l => {
      if (l.kind !== kind || !l.name) return;
      const e = locMap[l.name] || (locMap[l.name] = { name: l.name, kind: l.kind, parts: 0, units: 0 });
      e.parts += 1;
      e.units += (l.qty || 0);
    }));
  }
  const allLocs = Object.values(locMap).sort((a, b) => b.units - a.units || a.name.localeCompare(b.name));
  const locRows = q ? allLocs.filter(l => l.name.toLowerCase().includes(q.toLowerCase())) : allLocs;
  return (
    <div className="page">
      <div className="page-head">
        <div className="ph-titles"><div className="display" style={{ display: 'flex', alignItems: 'center', gap: 12 }}><Icon name="box" size={24} />Inventory</div>
          <div className="ph-sub">A transparent, live library of every electrical component on hand — backed by PartsBox. Same view for everyone.</div></div>
        <div className="ph-actions"><button className="btn primary" onClick={() => go({ screen: 'receiving' })}><Icon name="box" size={15} />Start receiving</button></div>
      </div>
      <div className="stat-row" style={{ marginBottom: 12 }}>
        <div className="stat"><div className="st-label"><Icon name="box" size={13} /> Distinct parts</div><div className="st-num">{stats.totalParts}</div><div className="st-sub">in the library</div></div>
        <div className="stat"><div className="st-label"><Icon name="layers" size={13} /> Units on hand</div><div className="st-num">{stats.totalUnits.toLocaleString()}</div><div className="st-sub">across all storage</div></div>
        <div className="stat"><div className="st-label"><Icon name="folder" size={13} /> Storage locations</div><div className="st-num">{stats.distinctBins}</div><div className="st-sub">wall bins + project boxes</div></div>
      </div>
      <div className="sync-bar"><span className="od-dot" /> Live · last synced just now <button className="btn sm ghost" style={{ marginLeft: 8 }}><Icon name="refresh" size={13} />Refresh</button>
        <span className="caption" style={{ marginLeft: 'auto' }}>PartsBox is the source of truth · every part links out</span></div>
      <div className="filterbar" style={{ margin: '12px 0', gap: 10, flexWrap: 'wrap' }}>
        <div className="seg-toggle">
          {[['all', 'All'], ['project', 'Project boxes'], ['wall', 'Development wall']].map(([k, l]) => (
            <button key={k} className={kind === k ? 'on' : ''} onClick={() => setKind(k)}>{l}</button>
          ))}
        </div>
        {/* PartsBox parts carry no category today, so `cats` collapses to just
            ['all'] and the dropdown offered a single meaningless option. Render
            it only when there is something to actually choose between. */}
        {!isLocView && cats.length > 1 && (
          <select className="select" value={cat} onChange={e => setCat(e.target.value)}>{cats.map(c => <option key={c} value={c}>{c === 'all' ? 'All categories' : c}</option>)}</select>
        )}
        <div className="searchfield" style={{ minWidth: 220 }}><Icon name="search" size={14} style={{ color: 'var(--text-muted)' }} />
          <input value={q} placeholder={isLocView ? 'Search location name…' : 'Search MPN, description…'} onChange={e => setQ(e.target.value)} /></div>
        <span className="caption" style={{ marginLeft: 'auto', alignSelf: 'center' }}>
          {isLocView
            ? `${locRows.length} of ${allLocs.length} ${kind === 'project' ? 'project boxes' : 'wall bins'}`
            : `${rows.length} of ${parts.length} parts`}
        </span>
      </div>
      {/* Loading is checked BEFORE the view branches: otherwise the locations
          view showed "No project boxes found" for the whole fetch, which reads
          as an empty account rather than work in progress. */}
      {(loading && parts.length === 0) ? (
        <div className="card"><EmptyState icon="box" title="Loading inventory from PartsBox…"
          sub="Fetching the full part list. This runs once, then is cached for a few minutes." /></div>
      ) : isLocView ? (
        locRows.length === 0 ? (
          <div className="card"><EmptyState icon="folder"
            title={q ? 'No storage locations match.' : `No ${kind === 'project' ? 'project boxes' : 'wall bins'} found.`}
            sub={q ? null : 'Locations appear here once PartsBox reports stock in them.'} /></div>
        ) : (
          <div className="tbl-wrap flow"><table className="bom">
            <thead><tr><th>Location</th><th className="num">Distinct parts</th><th className="num">Units on hand</th><th>Kind</th><th></th></tr></thead>
            <tbody>{locRows.map(l => (
              <tr key={l.name} style={{ cursor: 'pointer' }} onClick={() => go({ screen: 'storageDetail', id: l.name })}
                title="Open storage location">
                <td><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><Icon name="folder" size={14} style={{ color: 'var(--text-muted)' }} />
                  <span className="mono" style={{ fontWeight: 600 }}>{l.name}</span></div></td>
                <td className="num" style={{ fontWeight: 600 }}>{l.parts}</td>
                <td className="num">{l.units.toLocaleString()}</td>
                <td><span className={`loc-chip ${l.kind}`}>{l.kind === 'project' ? 'production' : 'development'}</span></td>
                <td style={{ textAlign: 'right' }}><Icon name="chevright" size={16} style={{ color: 'var(--text-muted)' }} /></td>
              </tr>
            ))}</tbody>
          </table></div>
        )
      ) : rows.length === 0 ? <div className="card"><EmptyState icon="box" title="No parts match." /></div> : (
        <div className="tbl-wrap flow"><table className="bom">
          <thead><tr><th>Part</th><th className="num">On hand</th><th>Storage</th><th>Tags</th><th></th></tr></thead>
          {/* Row key is p.id, not p.mpn: PartsBox legitimately holds several
              part records per MPN (9 dupes across 3121 parts). Duplicate keys
              make React tear down and rebuild rows instead of diffing them —
              a console warning on every Inventory visit, on an already-heavy
              3121-row table. p.id is unique for all 3121. */}
          <tbody>{rows.map(p => (
            <tr key={p.id || p.mpn}>
              <td><div className="mono" style={{ fontWeight: 600 }}>{p.mpn}{p.low && <span className="badge filled" style={{ background: 'var(--danger)', marginLeft: 8 }}><Icon name="alert" size={10} />LOW</span>}</div><div className="caption">{p.desc}{p.fp ? ` · ${p.fp}` : ''}</div></td>
              <td className="num" style={{ fontWeight: 600 }}>{p.onHand}</td>
              <td><div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>{p.locations.map((l, i) => <button key={i} className={`loc-chip ${l.kind}`} style={{ cursor: 'pointer', border: 0 }} onClick={() => go({ screen: 'storageDetail', id: l.name })} title="Open storage location">{l.name} · {l.qty}</button>)}</div></td>
              <td><div style={{ display: 'flex', gap: 5, flexWrap: 'wrap' }}>{(p.tags || []).map(t => <span key={t} className="tag-chip">{t}</span>)}</div></td>
              <td style={{ textAlign: 'right' }}>
                {p.url
                  ? <a className="btn sm ghost" href={p.url} target="_blank" rel="noopener noreferrer">Open in PartsBox ↗</a>
                  : <span className="caption">—</span>}
              </td>
            </tr>
          ))}</tbody>
        </table></div>
      )}
    </div>
  );
}

function ReceivingScreen({ go }) {
  return (
    <div className="page">
      <div className="page-head"><div className="ph-titles">
        <button className="btn-link" style={{ marginBottom: 8 }} onClick={() => go({ screen: 'inventoryEmbed' })}>← Inventory</button>
        <div className="display" style={{ display: 'flex', alignItems: 'center', gap: 12 }}><Icon name="box" size={24} />Receiving</div>
        <div className="ph-sub">Scanner-first. Scan any bag from any project or general stock, in any order — routing is automatic.</div></div></div>
      <div className="card" style={{ padding: 28, textAlign: 'center', maxWidth: 620, margin: '10px auto' }}>
        <div style={{ width: 56, height: 56, borderRadius: 14, background: 'var(--action-soft)', display: 'grid', placeItems: 'center', margin: '0 auto 14px', color: 'var(--action)' }}><Icon name="box" size={26} /></div>
        <div className="h2">Ready to scan</div>
        <p className="secondary" style={{ marginTop: 6 }}>Point the USB scanner at a bag's QR label. AutoBOM parses the CPN, checks for duplicates, routes by sigil, and writes stock to PartsBox.</p>
        <input className="input mono" style={{ marginTop: 14, textAlign: 'center' }} placeholder="Scanner input appears here…" autoFocus />
        <div className="caption" style={{ marginTop: 16 }}>Full receiving flow — scan cards, wall-bin disambiguation, duplicate detection — arrives in the Inventory Activation build.</div>
      </div>
    </div>
  );
}

/* ============================================================
   Programs (v4 — top-level org layer above Project)
   ============================================================ */
function ProgramsScreen({ go }) {
  const programs = useStore(s => s.programs || []);
  const projects = useStore(s => s.projects);
  const [showNew, setShowNew] = useStateEmb(false);
  return (
    <div className="page">
      <div className="page-head"><div className="ph-titles">
        <div className="display" style={{ display: 'flex', alignItems: 'center', gap: 12 }}><Icon name="folder" size={24} />Programs</div>
        <div className="ph-sub">The top of the hierarchy. A Program groups the Projects, Collections, and BOMs of one contract or product line.</div></div>
        <div className="ph-actions"><button className="btn primary" onClick={() => setShowNew(true)}><Icon name="plus" size={15} />New Program</button></div></div>
      <div className="prog-grid">
        {programs.map(p => (
          <button key={p.id} className="prog-card" onClick={() => go({ screen: 'programDetail', id: p.id })}>
            <div className="prog-card-head">
              <span className="prog-code">{p.identifier || p.code}</span>
              <span className={`badge outlined`} style={{ color: 'var(--success)', borderColor: 'var(--success)' }}>{p.status}</span>
            </div>
            <div className="prog-name">{p.name}</div>
            <div className="caption" style={{ margin: '4px 0 10px' }}>{p.desc}</div>
            <div className="prog-meta">
              <span><Icon name="user" size={12} /> {p.owner}</span>
              <span><Icon name="folder" size={12} /> {p.projects.length} project{p.projects.length === 1 ? '' : 's'}</span>
              {p.customer && <span><Icon name="sparkle" size={12} /> {p.customer}</span>}
            </div>
          </button>
        ))}
      </div>
      {showNew && <window.CreateProgramModal go={go} onClose={() => setShowNew(false)} />}
    </div>
  );
}

function ProgramDetailScreen({ id, go }) {
  const program = useStore(s => (s.programs || []).find(p => p.id === id));
  const activeRole = useStore(s => s.activeRole);
  const projects = useStore(s => s.projects);
  const collections = useStore(s => s.collections);
  const boms = useStore(s => s.boms);
  const [newColl, setNewColl] = useStateEmb(false);
  if (!program) return <div className="page"><EmptyState icon="folder" title="Program not found." actions={<button className="btn primary" onClick={() => go({ screen: 'programs' })}>All programs</button>} /></div>;
  // Guard every read: `projects`/`collections` can be empty mid-hydration and a
  // program with no linked projects has no `projects` array at all — an
  // unguarded .map/.includes there rendered the stat as blank (or threw).
  const programProjects = program.projects || [];
  const projRows = programProjects.map(pid => (projects || {})[pid]).filter(Boolean);
  // The API serializes this as `program`, not `program_id` — matching on the
  // latter never hit, so program-level Collections silently showed none.
  const progCollections = (collections || []).filter(c =>
    ((c.program || c.program_id) === program.id || programProjects.includes(c.project)) && c.role === 'designer');

  return (
    <div className="page">
      <div className="page-head"><div className="ph-titles">
        <button className="btn-link" style={{ marginBottom: 8 }} onClick={() => go({ screen: 'programs' })}>← Programs</button>
        <div className="display" style={{ display: 'flex', alignItems: 'center', gap: 12 }}><span className="prog-code lg">{program.code}</span>{program.name}</div>
        <div className="ph-sub">{program.desc}</div>
      </div></div>

      <div className="stat-row" style={{ marginBottom: 18 }}>
        <div className="stat"><div className="st-label"><Icon name="user" size={13} /> Owner</div><div className="st-num" style={{ fontSize: 18 }}>{program.owner}</div><div className="st-sub">{program.status}</div></div>
        <div className="stat"><div className="st-label"><Icon name="folder" size={13} /> PCB Projects</div><div className="st-num">{projRows.length}</div><div className="st-sub">under this program</div></div>
        <div className="stat"><div className="st-label"><Icon name="layers" size={13} /> Collections</div><div className="st-num">{progCollections.length}</div><div className="st-sub">exploration</div></div>
      </div>

      {activeRole === 'admin' && (
        <div className="card" style={{ padding: 14, marginBottom: 16, display: 'flex', alignItems: 'center', gap: 12 }}>
          <Icon name="bell" size={16} style={{ color: 'var(--text-muted)' }} />
          <div style={{ flex: 1 }}>
            <div style={{ fontWeight: 600 }}>Notify Program owner of equivalent-part swaps</div>
            <div className="caption">When on, Production's silent characteristic-match swaps on this Program's linked Projects send an FYI to {program.owner}. Override notifications always fire regardless.</div>
          </div>
          <button type="button" role="switch" aria-checked={program.notifyOnEquivalentSwap !== false} className={`switch${program.notifyOnEquivalentSwap !== false ? ' on' : ''}`} onClick={() => storeActions.setProgramNotify(program.id, !(program.notifyOnEquivalentSwap !== false))}><span className="knob" /></button>
        </div>
      )}

      <div className="panel">
        <div className="panel-head"><Icon name="folder" size={15} /><span className="ph-title">PCB Projects</span><span className="ph-meta" style={{ marginLeft: 'auto' }}>Read-only references · Production owns Projects</span></div>
        <div className="tbl-wrap flow" style={{ border: 0 }}><table className="bom">
          <thead><tr><th>Reference</th><th>Name</th><th>Status</th><th>Lead</th></tr></thead>
          <tbody>{projRows.map(pr => (
            <tr key={pr.id} style={{ cursor: 'pointer' }} onClick={() => go({ screen: 'projectDetail', id: pr.id })}>
              <td className="mono" style={{ fontWeight: 600 }}>{(program.identifier || program.code)}-{pr.identifier || pr.id.slice(0, 4).toUpperCase()}</td>
              <td>{pr.name}</td>
              <td><span className="badge outlined" style={{ color: 'var(--success)' }}>{pr.status}</span></td>
              <td>{pr.lead}</td>
            </tr>
          ))}</tbody>
        </table></div>
      </div>

      <div className="panel" style={{ marginTop: 16 }}>
        <div className="panel-head"><Icon name="layers" size={15} style={{ color: 'var(--role-designer)' }} /><span className="ph-title">Collections at program level</span>
          <button className="btn sm primary" style={{ marginLeft: 'auto' }} onClick={() => setNewColl(true)}><Icon name="plus" size={14} />New Collection</button></div>
        {progCollections.length === 0 ? <EmptyState icon="layers" title="No collections yet." sub="Create a collection to gather candidate parts for this program." /> : (
          <div style={{ padding: 8 }}>{progCollections.map(c => (
            <div key={c.id} className="prog-coll-row" onClick={() => go({ screen: 'd.collectionDetail', id: c.id })}>
              <Icon name="layers" size={15} style={{ color: 'var(--role-designer)' }} />
              <span style={{ fontWeight: 600 }}>{c.name}</span>
              <span className="caption">{(c.project && projects[c.project]) ? projects[c.project].name : program.name} · {c.items.length} parts</span>
              <StatusBadge status={c.state} />
            </div>
          ))}</div>
        )}
      </div>
      {newColl && <window.NewCollectionModal kind="designer" defaultProgram={program.id} onClose={() => setNewColl(false)} onCreated={(cid) => { setNewColl(false); go({ screen: 'd.collectionDetail', id: cid }); }} />}
    </div>
  );
}

/* ============================================================
   Storage location detail (v4 — new build, first-class route)
   Inventory · Storage locations · <name>. Reads PartsBox contents live.
   ============================================================ */
function StorageDetailScreen({ id, go }) {
  const name = id;
  const inventory = useStore(s => s.inventory || []);
  const rows = [];
  let kind = 'wall';
  inventory.forEach(p => (p.locations || []).forEach(l => {
    if (l.name === name) { rows.push({ mpn: p.mpn, desc: p.desc, qty: l.qty, onHand: p.onHand, cat: p.cat, low: p.low, url: p.url }); if (l.kind === 'project') kind = 'project'; }
  }));
  const units = rows.reduce((a, r) => a + (r.qty || 0), 0);
  const tag = kind === 'project' ? 'production' : 'development';
  if (rows.length === 0) return <div className="page"><EmptyState icon="folder" title="Storage location not found." sub={name}
    actions={<button className="btn primary" onClick={() => go({ screen: 'inventoryEmbed' })}>Back to Inventory</button>} /></div>;
  return (
    <div className="page">
      <div className="page-head">
        <div className="ph-titles">
          <button className="btn-link" style={{ marginBottom: 8 }} onClick={() => go({ screen: 'inventoryEmbed' })}>← Inventory</button>
          <div className="display" style={{ display: 'flex', alignItems: 'center', gap: 12 }}><Icon name="folder" size={22} /><span className="mono">{name}</span></div>
          <div className="ph-sub">A PartsBox storage location. AutoBOM reads its contents live — this view never leaves the app.</div>
        </div>
        <div className="ph-actions" style={{ display: 'flex', gap: 8 }}>
          <button className="btn" onClick={() => go({ screen: 'receiving' })}><Icon name="plus" size={15} />Add stock</button>
          <button className="btn" onClick={() => window.__toast?.('Move parts arrives with the receiving rebuild.', 'box')}><Icon name="arrow" size={15} />Move parts</button>
        </div>
      </div>
      <div className="stat-row" style={{ marginBottom: 12 }}>
        <div className="stat"><div className="st-label"><Icon name="box" size={13} /> Distinct parts</div><div className="st-num">{rows.length}</div><div className="st-sub">stored here</div></div>
        <div className="stat"><div className="st-label"><Icon name="layers" size={13} /> Units on hand</div><div className="st-num">{units.toLocaleString()}</div><div className="st-sub">in this location</div></div>
        <div className="stat"><div className="st-label"><Icon name="tag" size={13} /> Storage kind</div><div className="st-num" style={{ fontSize: 17 }}>{kind === 'project' ? 'Project box' : 'Development wall'}</div><div className="st-sub"><span className={`loc-chip ${kind}`}>{tag}</span></div></div>
      </div>
      <div className="sync-bar"><span className="od-dot" /> Live · PartsBox is the source of truth<span className="caption" style={{ marginLeft: 'auto' }}>Every part links out to its PartsBox record</span></div>
      <div className="tbl-wrap flow" style={{ marginTop: 12 }}><table className="bom">
        <thead><tr><th>Part</th><th className="num">Qty here</th><th className="num">Total on hand</th><th>Category</th><th></th></tr></thead>
        <tbody>{rows.map(r => (
          <tr key={r.mpn}>
            <td><div className="mono" style={{ fontWeight: 600 }}>{r.mpn}{r.low && <span className="badge filled" style={{ background: 'var(--danger)', marginLeft: 8 }}><Icon name="alert" size={10} />LOW</span>}</div><div className="caption">{r.desc}</div></td>
            <td className="num" style={{ fontWeight: 600 }}>{r.qty}</td>
            <td className="num">{r.onHand}</td>
            <td className="caption">{r.cat || '—'}</td>
            <td style={{ textAlign: 'right' }}>
              {r.url
                ? <a className="btn sm ghost" href={r.url} target="_blank" rel="noopener noreferrer">Open in PartsBox ↗</a>
                : <span className="caption">—</span>}
            </td>
          </tr>
        ))}</tbody>
      </table></div>
    </div>
  );
}

Object.assign(window, { EmbeddedPurchasing, EmbeddedInventory, ReceivingScreen, StorageDetailScreen, ProgramsScreen, ProgramDetailScreen });
